insert into public.search_queries (query, count) values
('polyatomic ions', 1),
('unit circle', 1),
('java primitive types', 1),
('autoboxing java', 1),
('valence electrons', 1),
('electron configurations', 1),
('ionic compounds', 1),
('periodic trends', 1),
('first ionization energy', 1),
('java string concatination', 1),
('java string addition', 1),
('adding strings in java', 1),
('concatinating strings in java', 1),
('charges of polyatomic ions', 1);
